// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPMuGg2C0cUgBoErXlQZMD3c6mjFMUFq4',
    appId: '1:183454279490:web:5ea4e5f01766b071198adb',
    messagingSenderId: '183454279490',
    projectId: 'real-estate-5753e',
    authDomain: 'real-estate-5753e.firebaseapp.com',
    storageBucket: 'real-estate-5753e.firebasestorage.app',
    measurementId: 'G-WZCVLL197K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOfPT2kYJStXsAKikTK0ljt_A7aD2-y5U',
    appId: '1:183454279490:android:2ea2c3f818103897198adb',
    messagingSenderId: '183454279490',
    projectId: 'real-estate-5753e',
    storageBucket: 'real-estate-5753e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpXSZTNQzdIGt0hCMxlgMhHzFYab6yUbc',
    appId: '1:183454279490:ios:f87112bef5e99dd8198adb',
    messagingSenderId: '183454279490',
    projectId: 'real-estate-5753e',
    storageBucket: 'real-estate-5753e.firebasestorage.app',
    iosBundleId: 'com.example.realEstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpXSZTNQzdIGt0hCMxlgMhHzFYab6yUbc',
    appId: '1:183454279490:ios:f87112bef5e99dd8198adb',
    messagingSenderId: '183454279490',
    projectId: 'real-estate-5753e',
    storageBucket: 'real-estate-5753e.firebasestorage.app',
    iosBundleId: 'com.example.realEstate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPMuGg2C0cUgBoErXlQZMD3c6mjFMUFq4',
    appId: '1:183454279490:web:1fa8f6607f0e980c198adb',
    messagingSenderId: '183454279490',
    projectId: 'real-estate-5753e',
    authDomain: 'real-estate-5753e.firebaseapp.com',
    storageBucket: 'real-estate-5753e.firebasestorage.app',
    measurementId: 'G-HMDZVR3DXJ',
  );
}
